"""Builds the Containerlab topology (drishti.clab.yml) from data/topology.json.
Interface names come from the shared addressing.interface_plan so endpoints match
the FRR configs generated by frr.py."""
from __future__ import annotations

import yaml

from twin.addressing import interface_plan


def build_clab(topology: dict, node_image: str, mgmt_subnet: str) -> dict:
    plan = interface_plan(topology)
    nodes: dict[str, dict] = {}
    for node in topology["nodes"]:
        nid = node["id"]
        nodes[nid] = {
            "kind": "linux",
            "image": node_image,
            "binds": [f"configs/{nid}/frr.conf:/etc/frr/frr.conf"],
        }
    links: list[dict] = []
    for link in topology["links"]:
        a_node, b_node = link["a"]["node"], link["b"]["node"]
        a_if = next(i["ifname"] for i in plan[a_node] if i["link_id"] == link["id"])
        b_if = next(i["ifname"] for i in plan[b_node] if i["link_id"] == link["id"])
        links.append({"endpoints": [f"{a_node}:{a_if}", f"{b_node}:{b_if}"]})
    return {
        "name": "drishti",
        "mgmt": {"network": "drishti-mgmt", "ipv4-subnet": mgmt_subnet},
        "topology": {"nodes": nodes, "links": links},
    }


def to_yaml(clab: dict) -> str:
    return yaml.safe_dump(clab, sort_keys=False, default_flow_style=False)
